version: 2
jobs:
  build:
    docker:
    - image: tiryoh/ubuntu:dev-bionic
    steps:
    - checkout
    - run:
        name: Install
        command: ./run.sh
    - run:
        name: Test
        command: source ./.circleci/test.sh

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 1 * * 1"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
